services:
  taskmanager.api:
    image: ${DOCKER_REGISTRY-}taskmanagerapi
    build:
      context: .
      dockerfile: TaskManager.Api/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - api_network
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: taskmanager
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d password"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - api_network

volumes:
  pgdata:

networks:
  api_network:
